using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class InteractionSystem : MonoBehaviour
{
    public Transform detectionPoint;
    private const float detectionRadius = 0.2f;
    public LayerMask detectionLayer;

    public GameObject detectedObject;

    public List<GameObject> pickedItems = new List<GameObject>();

    void Update()
    {
        if(DetectObject())
        {
            if(InteractionInput())
            {
                detectedObject.GetComponent<Item>().Interact();
            }
        }
    }

    bool InteractionInput()
    {
        return Input.GetKeyDown(KeyCode.E);
    }

    bool DetectObject()
    {
        Collider2D obj = Physics2D.OverlapCircle(detectionPoint.position, detectionRadius, detectionLayer);
        if(obj == null)
        {
            detectedObject = null;
            return false;
        }
        else
        {
            detectedObject = obj.gameObject;
            return true;
        }
    }

    public void ItemPickUp(GameObject item)
    {
        pickedItems.Add(item);
    }
}
